name: Ffmpeg builds

on :
  push:
    branches:
      - main
  schedule:
    - cron: 00 02 * * *

jobs:
  ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get the tar file
        run: |
          rm -rf ff*.tar.xz
          wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
          wget https://github.com/P3TERX/Aria2-Pro-Core/releases/latest/download/aria2-1.36.0-static-linux-amd64.tar.gz && tar xzf aria2*.tar.gz && rm -rf *.gz
          git add .
    
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Cron"
          commit_options: "--no-verify"
          repository: .
