name: Ffmpeg builds

on :
  push:
    branches:
      - main
  schedule:
    - cron: 00 02 * * *

jobs:
  ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: get the tar file
        run: |
          rm -rf ff*.tar.xz
          wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
          git add .
    
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Cron"
          commit_options: "--no-verify"
          repository: .
